eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: http://65.1.247.97:8761/eureka/
      defaultZone: http://localhost:8761/eureka/
  instance.hostname: localhost
